import Head from "next/head";
import Link from "next/link";
import { FormattedMessage } from "react-intl";
import { BsQrCode } from "react-icons/bs";
import React, { useEffect, useState } from "react";
import Image from "next/image";

export default function Home({ dir }) {
  return (
    <>
      <Head>
        <title>Flight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/newcashlogo.svg" />
        <link rel="alternate" href="http://example.com" hrefLang="x-default" />
        <link rel="alternate" href="http://example.com" hrefLang="en" />
        <link rel="alternate" href="http://example.com/ar" hrefLang="ar" />
        <link rel="alternate" href="http://example.com/fa" hrefLang="fa" />
      </Head>

      <div className="grid place-content-center h-screen">
        <div className="card w-96 bg-base-100 shadow-xl">
          <div className="card-body grid place-content-center">
            <Image src="/qr-code.png" width="250" height="250" />
            <div className="grid place-content-center">
              <Link href="/Search">
                <button className=" btn text-lg my-10 font-bold">
                  Scan this with your phone!
                </button>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
